// ── Shared primal engine templates ─────────────────────────────────────────────
//
// Single source of truth for all AnimalTemplate definitions.
// Importing this module boots PrimalEngine exactly once via ES module caching —
// regardless of how many page components import it.
//
// DO NOT modify PrimalEngine, ZoneIntelligence, Ontology, or ChefDecisionEngine.

import { PrimalEngine, type AnimalTemplate } from "./primal-engine";

// ── Beef ───────────────────────────────────────────────────────────────────────

export const ENGINE_COW: AnimalTemplate = {
  id: "cow",
  label: "Beef",
  anchors: [
    { id: "H1",  x: 0.15, y: 0.60, role: "head rear-top",             layer: "HEAD" },
    { id: "H2",  x: 0.22, y: 0.70, role: "head top",                  layer: "HEAD" },
    { id: "H3",  x: 0.30, y: 0.62, role: "poll",                      layer: "HEAD" },
    { id: "H4",  x: 0.25, y: 0.50, role: "head bottom",               layer: "HEAD" },
    { id: "HR1", x: 0.18, y: 0.72, role: "horn root",                 layer: "HEAD" },
    { id: "HR2", x: 0.28, y: 0.78, role: "horn tip",                  layer: "HEAD" },
    { id: "T1",  x: 0.32, y: 0.65, role: "neck-body junction top",    layer: "BODY" },
    { id: "C1",  x: 0.52, y: 0.68, role: "chuck-rib division top",    layer: "BODY" },
    { id: "RL1", x: 0.63, y: 0.68, role: "rib-loin division top",     layer: "BODY" },
    { id: "SL1", x: 0.73, y: 0.67, role: "loin-round division top",   layer: "BODY" },
    { id: "T2",  x: 0.80, y: 0.68, role: "topline rear",              layer: "BODY" },
    { id: "T3",  x: 0.85, y: 0.55, role: "rump",                      layer: "BODY" },
    { id: "T4",  x: 0.78, y: 0.42, role: "hindquarter bottom",        layer: "BODY" },
    { id: "SL2", x: 0.73, y: 0.43, role: "loin-round division bot",   layer: "BODY" },
    { id: "RL2", x: 0.63, y: 0.44, role: "rib-loin division bottom",  layer: "BODY" },
    { id: "C2",  x: 0.52, y: 0.44, role: "chuck-rib division bottom", layer: "BODY" },
    { id: "T5",  x: 0.30, y: 0.45, role: "neck-body junction bottom", layer: "BODY" },
    { id: "BK1", x: 0.33, y: 0.28, role: "brisket tip",               layer: "BODY" },
    { id: "BK2", x: 0.52, y: 0.26, role: "brisket-plate junction",    layer: "BODY" },
    { id: "PL1", x: 0.63, y: 0.26, role: "plate-flank junction",      layer: "BODY" },
    { id: "FL1", x: 0.74, y: 0.27, role: "flank anchor",              layer: "BODY" },
    { id: "L1",  x: 0.35, y: 0.30, role: "foreleg top",               layer: "LIMB" },
    { id: "L2",  x: 0.45, y: 0.30, role: "foreleg",                   layer: "LIMB" },
    { id: "LSH", x: 0.40, y: 0.14, role: "fore shank",                layer: "LIMB" },
    { id: "L3",  x: 0.65, y: 0.30, role: "hindleg top",               layer: "LIMB" },
    { id: "L4",  x: 0.75, y: 0.30, role: "hindleg",                   layer: "LIMB" },
    { id: "LHH", x: 0.70, y: 0.14, role: "hind shank",                layer: "LIMB" },
  ],
  edges: [
    ["H1","H2"],["H2","H3"],["H3","H4"],["H4","H1"],
    ["HR1","HR2"],["HR2","H2"],
    ["H2","T1"],
    ["T1","C1"],["C1","RL1"],["RL1","SL1"],["SL1","T2"],
    ["T2","T3"],["T3","T4"],
    ["T4","SL2"],["SL2","RL2"],["RL2","C2"],["C2","T5"],["T5","T1"],
    ["C1","C2"],["RL1","RL2"],["SL1","SL2"],
    ["T5","BK1"],["BK1","BK2"],["BK2","C2"],
    ["BK2","PL1"],["PL1","RL2"],
    ["PL1","FL1"],["FL1","SL2"],
    ["L1","L2"],["L2","L3"],["L3","L4"],
    ["T5","L1"],["T4","L3"],
    ["L1","LSH"],["LSH","L2"],
    ["L3","LHH"],["LHH","L4"],
  ],
  allowedEdges: [
    ["H1","H2"],["H2","H3"],["H3","H4"],["H4","H1"],
    ["HR1","HR2"],["HR2","H2"],
    ["H2","T1"],
    ["T1","C1"],["C1","RL1"],["RL1","SL1"],["SL1","T2"],
    ["T2","T3"],["T3","T4"],
    ["T4","SL2"],["SL2","RL2"],["RL2","C2"],["C2","T5"],["T5","T1"],
    ["C1","C2"],["RL1","RL2"],["SL1","SL2"],
    ["T5","BK1"],["BK1","BK2"],["BK2","C2"],
    ["BK2","PL1"],["PL1","RL2"],
    ["PL1","FL1"],["FL1","SL2"],
    ["L1","L2"],["L2","L3"],["L3","L4"],
    ["T5","L1"],["T4","L3"],
    ["L1","LSH"],["LSH","L2"],
    ["L3","LHH"],["LHH","L4"],
  ],
  zones: [
    { id: "head",       label: "Head",       layer: "HEAD", anchors: ["H1","H2","H3","H4"],        colorToken: "HEAD_ZONE"     },
    { id: "chuck",      label: "Chuck",      layer: "BODY", anchors: ["T1","C1","C2","T5"],        colorToken: "SHOULDER_ZONE" },
    { id: "brisket",    label: "Brisket",    layer: "BODY", anchors: ["T5","BK1","BK2","C2"],      colorToken: "BELLY_ZONE",    silhouetteRegionId: "chuck"      },
    { id: "rib",        label: "Rib",        layer: "BODY", anchors: ["C1","RL1","RL2","C2"],      colorToken: "RIB_ZONE"      },
    { id: "plate",      label: "Plate",      layer: "BODY", anchors: ["C2","RL2","PL1","BK2"],     colorToken: "BELLY_ZONE",    silhouetteRegionId: "rib"        },
    { id: "short_loin", label: "Short Loin", layer: "BODY", anchors: ["RL1","SL1","SL2","RL2"],    colorToken: "LOIN_ZONE"     },
    { id: "flank",      label: "Flank",      layer: "BODY", anchors: ["RL2","SL2","FL1","PL1"],    colorToken: "BELLY_ZONE",    silhouetteRegionId: "short_loin" },
    { id: "round",      label: "Round",      layer: "BODY", anchors: ["SL1","T2","T3","T4","SL2"], colorToken: "LEG_ZONE"      },
    { id: "fore_shank", label: "Fore Shank", layer: "LIMB", anchors: ["L1","L2","LSH"],             colorToken: "HEAD_ZONE"     },
    { id: "hind_shank", label: "Hind Shank", layer: "LIMB", anchors: ["L3","L4","LHH"],             colorToken: "HEAD_ZONE"     },
  ],
};

// ── Pork ───────────────────────────────────────────────────────────────────────

export const ENGINE_PIG: AnimalTemplate = {
  id: "pig",
  label: "Pork",
  anchors: [
    { id: "SN",  x: 0.08, y: 0.62, role: "snout",           layer: "HEAD"      },
    { id: "H1",  x: 0.13, y: 0.72, role: "head top",        layer: "HEAD"      },
    { id: "H2",  x: 0.13, y: 0.52, role: "head bottom",     layer: "HEAD"      },
    { id: "JW",  x: 0.23, y: 0.62, role: "jowl rear",       layer: "HEAD"      },
    { id: "NK",  x: 0.25, y: 0.68, role: "neck",            layer: "BODY"      },
    { id: "SH",  x: 0.33, y: 0.76, role: "shoulder top",    layer: "BODY"      },
    { id: "SL",  x: 0.33, y: 0.55, role: "shoulder bottom", layer: "BODY"      },
    { id: "BT",  x: 0.58, y: 0.78, role: "loin top",        layer: "BODY"      },
    { id: "BB",  x: 0.58, y: 0.54, role: "loin bottom",     layer: "BODY"      },
    { id: "HT",  x: 0.78, y: 0.74, role: "ham top",         layer: "BODY"      },
    { id: "HB",  x: 0.78, y: 0.54, role: "ham bottom",      layer: "BODY"      },
    { id: "BL",  x: 0.36, y: 0.42, role: "belly front",     layer: "BODY"      },
    { id: "BM",  x: 0.60, y: 0.40, role: "belly mid",       layer: "BODY"      },
    { id: "TL",  x: 0.87, y: 0.65, role: "tail",            layer: "APPENDAGE" },
    { id: "HH1", x: 0.60, y: 0.28, role: "hind hock top",   layer: "LIMB"      },
    { id: "HH2", x: 0.67, y: 0.28, role: "hind hock base",  layer: "LIMB"      },
    { id: "HHT", x: 0.63, y: 0.14, role: "hind trotter",    layer: "LIMB"      },
  ],
  edges: [
    ["SN","H1"],["SN","H2"],["H1","JW"],["JW","H2"],["JW","NK"],
    ["NK","SH"],["SH","SL"],["SL","NK"],
    ["SH","BT"],["BT","HT"],["HT","TL"],
    ["SL","BB"],["BB","HB"],["HB","TL"],
    ["BT","BB"],["HT","HB"],
    ["SL","BL"],["BL","BM"],["BM","HB"],
    ["BM","HH1"],["HH1","HH2"],["HH1","HHT"],["HH2","HHT"],
  ],
  allowedEdges: [
    ["SN","H1"],["SN","H2"],["H1","JW"],["JW","H2"],["JW","NK"],
    ["NK","SH"],["SH","SL"],["SL","NK"],
    ["SH","BT"],["BT","HT"],["HT","TL"],
    ["SL","BB"],["BB","HB"],["HB","TL"],
    ["BT","BB"],["HT","HB"],
    ["SL","BL"],["BL","BM"],["BM","HB"],
    ["BM","HH1"],["HH1","HH2"],["HH1","HHT"],["HH2","HHT"],
  ],
  zones: [
    { id: "head",      label: "Head",      layer: "HEAD", anchors: ["SN","H1","H2"],        colorToken: "HEAD_ZONE"     },
    { id: "jowl",      label: "Jowl",      layer: "HEAD", anchors: ["H1","JW","H2"],        colorToken: "RIB_ZONE",      silhouetteRegionId: "head" },
    { id: "shoulder",  label: "Shoulder",  layer: "BODY", anchors: ["NK","SH","SL"],        colorToken: "SHOULDER_ZONE" },
    { id: "loin",      label: "Loin",      layer: "BODY", anchors: ["SH","BT","BB","SL"],   colorToken: "LOIN_ZONE"     },
    { id: "belly",     label: "Belly",     layer: "BODY", anchors: ["SL","BL","BM","HB"],   colorToken: "BELLY_ZONE"    },
    { id: "ham",       label: "Ham",       layer: "BODY", anchors: ["BT","HT","HB","BB"],   colorToken: "LEG_ZONE"      },
    { id: "hind_hock", label: "Hind Hock", layer: "LIMB", anchors: ["HH1","HH2","HHT"],     colorToken: "HEAD_ZONE"     },
  ],
};

// ── Chicken / Poultry ──────────────────────────────────────────────────────────

export const ENGINE_CHICKEN: AnimalTemplate = {
  id: "chicken",
  label: "Poultry",
  anchors: [
    { id: "BK",  x: 0.08, y: 0.65, role: "beak",                layer: "HEAD"      },
    { id: "HD",  x: 0.16, y: 0.74, role: "head crown",          layer: "HEAD"      },
    { id: "NK",  x: 0.26, y: 0.70, role: "neck join",           layer: "HEAD"      },
    { id: "CT",  x: 0.48, y: 0.74, role: "chest/keel top",      layer: "BODY"      },
    { id: "CB",  x: 0.48, y: 0.60, role: "chest/keel bottom",   layer: "BODY"      },
    { id: "BK1", x: 0.65, y: 0.73, role: "back mid-top",        layer: "BODY"      },
    { id: "BK2", x: 0.65, y: 0.59, role: "back mid-bottom",     layer: "BODY"      },
    { id: "TL",  x: 0.80, y: 0.76, role: "tail top",            layer: "BODY"      },
    { id: "TR",  x: 0.80, y: 0.65, role: "tail bottom",         layer: "BODY"      },
    { id: "LG1", x: 0.52, y: 0.48, role: "thigh top",           layer: "LIMB"      },
    { id: "THP", x: 0.62, y: 0.52, role: "thigh outer",         layer: "LIMB"      },
    { id: "LG2", x: 0.55, y: 0.33, role: "knee",                layer: "LIMB"      },
    { id: "DKP", x: 0.63, y: 0.33, role: "drumstick outer",     layer: "LIMB"      },
    { id: "LG3", x: 0.57, y: 0.18, role: "foot/tarsus",         layer: "LIMB"      },
    { id: "WSU", x: 0.46, y: 0.76, role: "wing shoulder upper", layer: "APPENDAGE" },
    { id: "WEU", x: 0.40, y: 0.89, role: "wing elbow upper",    layer: "APPENDAGE" },
    { id: "WTU", x: 0.58, y: 0.95, role: "wing tip upper",      layer: "APPENDAGE" },
    { id: "WSL", x: 0.46, y: 0.58, role: "wing shoulder lower", layer: "APPENDAGE" },
    { id: "WEL", x: 0.40, y: 0.46, role: "wing elbow lower",    layer: "APPENDAGE" },
    { id: "WTL", x: 0.58, y: 0.40, role: "wing tip lower",      layer: "APPENDAGE" },
  ],
  edges: [
    ["BK","HD"],["HD","NK"],
    ["NK","CT"],["CT","BK1"],["BK1","TL"],
    ["NK","CB"],["CB","BK2"],["BK2","TR"],
    ["CT","CB"],["BK1","BK2"],["TL","TR"],
    ["CB","LG1"],
    ["LG1","THP"],["THP","LG2"],
    ["LG1","LG2"],["LG2","LG3"],
    ["LG2","DKP"],["DKP","LG3"],
    ["CT","WSU"],["WSU","WEU"],["WEU","WTU"],
    ["CB","WSL"],["WSL","WEL"],["WEL","WTL"],
    ["WSU","WSL"],
  ],
  allowedEdges: [
    ["BK","HD"],["HD","NK"],
    ["NK","CT"],["CT","BK1"],["BK1","TL"],
    ["NK","CB"],["CB","BK2"],["BK2","TR"],
    ["CT","CB"],["BK1","BK2"],["TL","TR"],
    ["CB","LG1"],
    ["LG1","THP"],["THP","LG2"],
    ["LG1","LG2"],["LG2","LG3"],
    ["LG2","DKP"],["DKP","LG3"],
    ["CT","WSU"],["WSU","WEU"],["WEU","WTU"],
    ["CB","WSL"],["WSL","WEL"],["WEL","WTL"],
    ["WSU","WSL"],
  ],
  zones: [
    { id: "crown",     label: "Head",      layer: "HEAD",      anchors: ["BK","HD","NK"],                      colorToken: "HEAD_ZONE"  },
    { id: "breast",    label: "Breast",    layer: "BODY",      anchors: ["CT","BK1","BK2","CB"],               colorToken: "LOIN_ZONE"  },
    { id: "back",      label: "Back",      layer: "BODY",      anchors: ["BK1","TL","TR","BK2"],               colorToken: "BELLY_ZONE" },
    { id: "wing",      label: "Wing",      layer: "APPENDAGE", anchors: ["WSU","WEU","WTU","WTL","WEL","WSL"], colorToken: "RIB_ZONE"   },
    { id: "thigh",     label: "Thigh",     layer: "LIMB",      anchors: ["LG1","THP","LG2"],                   colorToken: "LEG_ZONE"   },
    { id: "drumstick", label: "Drumstick", layer: "LIMB",      anchors: ["LG2","DKP","LG3"],                   colorToken: "LEG_ZONE",   silhouetteRegionId: "thigh" },
  ],
};

// ── Lamb ───────────────────────────────────────────────────────────────────────

export const ENGINE_LAMB: AnimalTemplate = {
  id: "lamb",
  label: "Lamb",
  anchors: [
    { id: "MZ",   x: 0.06, y: 0.64, role: "muzzle",          layer: "HEAD" },
    { id: "H1",   x: 0.12, y: 0.73, role: "head top",        layer: "HEAD" },
    { id: "H2",   x: 0.12, y: 0.56, role: "head bottom",     layer: "HEAD" },
    { id: "NK1",  x: 0.22, y: 0.80, role: "neck top",        layer: "BODY" },
    { id: "NK2",  x: 0.22, y: 0.62, role: "neck bottom",     layer: "BODY" },
    { id: "SH",   x: 0.34, y: 0.82, role: "shoulder top",    layer: "BODY" },
    { id: "SB",   x: 0.34, y: 0.60, role: "shoulder bottom", layer: "BODY" },
    { id: "R1",   x: 0.54, y: 0.82, role: "rack top",        layer: "BODY" },
    { id: "R2",   x: 0.54, y: 0.60, role: "rack bottom",     layer: "BODY" },
    { id: "LN",   x: 0.68, y: 0.80, role: "loin top",        layer: "BODY" },
    { id: "LB",   x: 0.68, y: 0.60, role: "loin bottom",     layer: "BODY" },
    { id: "TL",   x: 0.87, y: 0.67, role: "tail/rump",       layer: "BODY" },
    { id: "BR1",  x: 0.36, y: 0.44, role: "breast front",    layer: "BODY" },
    { id: "BR2",  x: 0.70, y: 0.44, role: "breast rear",     layer: "BODY" },
    { id: "LG1",  x: 0.80, y: 0.76, role: "leg top",         layer: "LIMB" },
    { id: "LG2",  x: 0.80, y: 0.56, role: "leg bottom",      layer: "LIMB" },
    { id: "LG3",  x: 0.82, y: 0.38, role: "cannon bone",     layer: "LIMB" },
    { id: "LSH",  x: 0.79, y: 0.20, role: "shank left",      layer: "LIMB" },
    { id: "LSH2", x: 0.86, y: 0.20, role: "shank right",     layer: "LIMB" },
  ],
  edges: [
    ["MZ","H1"],["MZ","H2"],["H1","NK1"],["H2","NK2"],
    ["NK1","SH"],["NK2","SB"],["SH","SB"],
    ["SH","R1"],["R1","LN"],["LN","LG1"],["LG1","TL"],
    ["SB","R2"],["R2","LB"],["LB","LG2"],["LG2","TL"],
    ["R1","R2"],["LN","LB"],["LG1","LG2"],
    ["SB","BR1"],["BR1","BR2"],["BR2","LG2"],
    ["LG2","LG3"],["LG3","LSH"],["LG3","LSH2"],["LSH","LSH2"],
  ],
  allowedEdges: [
    ["MZ","H1"],["MZ","H2"],["H1","NK1"],["H2","NK2"],
    ["NK1","SH"],["NK2","SB"],["SH","SB"],
    ["SH","R1"],["R1","LN"],["LN","LG1"],["LG1","TL"],
    ["SB","R2"],["R2","LB"],["LB","LG2"],["LG2","TL"],
    ["R1","R2"],["LN","LB"],["LG1","LG2"],
    ["SB","BR1"],["BR1","BR2"],["BR2","LG2"],
    ["LG2","LG3"],["LG3","LSH"],["LG3","LSH2"],["LSH","LSH2"],
  ],
  zones: [
    { id: "head",     label: "Head",     layer: "HEAD", anchors: ["MZ","H1","H2"],          colorToken: "HEAD_ZONE"     },
    { id: "shoulder", label: "Shoulder", layer: "BODY", anchors: ["NK1","SH","SB","NK2"],   colorToken: "SHOULDER_ZONE" },
    { id: "rack",     label: "Rack",     layer: "BODY", anchors: ["SH","R1","R2","SB"],     colorToken: "RIB_ZONE"      },
    { id: "loin",     label: "Loin",     layer: "BODY", anchors: ["R1","LN","LB","R2"],     colorToken: "LOIN_ZONE"     },
    { id: "breast",   label: "Breast",   layer: "BODY", anchors: ["SB","BR1","BR2"],         colorToken: "BELLY_ZONE"    },
    { id: "leg",      label: "Leg",      layer: "LIMB", anchors: ["LG1","LG2","LG3"],        colorToken: "LEG_ZONE"      },
    { id: "shank",    label: "Shank",    layer: "LIMB", anchors: ["LG3","LSH","LSH2"],       colorToken: "HEAD_ZONE",     silhouetteRegionId: "leg" },
  ],
};

// ── Fish ───────────────────────────────────────────────────────────────────────
// Kept for the standalone /primal-butcher debug route.
// Fish is NOT part of the Butchery Board — it belongs to Seafood Fabrication.

export const ENGINE_FISH: AnimalTemplate = {
  id: "fish",
  label: "Fish",
  anchors: [
    { id: "MT",  x: 0.06, y: 0.64, role: "mouth top",         layer: "HEAD" },
    { id: "MB",  x: 0.06, y: 0.57, role: "mouth bottom",      layer: "HEAD" },
    { id: "HD",  x: 0.16, y: 0.72, role: "head top",          layer: "HEAD" },
    { id: "HB",  x: 0.16, y: 0.52, role: "head bottom",       layer: "HEAD" },
    { id: "GI",  x: 0.28, y: 0.74, role: "gill plate top",    layer: "BODY" },
    { id: "GB",  x: 0.28, y: 0.50, role: "gill plate bottom", layer: "BODY" },
    { id: "BT",  x: 0.55, y: 0.72, role: "body top",          layer: "BODY" },
    { id: "BB",  x: 0.55, y: 0.50, role: "body bottom",       layer: "BODY" },
    { id: "BEL", x: 0.42, y: 0.36, role: "belly anchor",      layer: "BODY" },
    { id: "T1",  x: 0.76, y: 0.72, role: "wrist top",         layer: "BODY" },
    { id: "T2",  x: 0.76, y: 0.50, role: "wrist bottom",      layer: "BODY" },
    { id: "TCP", x: 0.82, y: 0.62, role: "tail peduncle",     layer: "BODY" },
    { id: "DF",  x: 0.46, y: 0.84, role: "dorsal fin apex",   layer: "FIN"  },
    { id: "PF",  x: 0.40, y: 0.44, role: "pectoral fin",      layer: "FIN"  },
    { id: "TT",  x: 0.88, y: 0.82, role: "tail fan top",      layer: "FIN"  },
    { id: "TM",  x: 0.92, y: 0.62, role: "tail fan mid",      layer: "FIN"  },
    { id: "TB",  x: 0.88, y: 0.42, role: "tail fan bottom",   layer: "FIN"  },
  ],
  edges: [
    ["MT","HD"],["MB","HB"],["MT","MB"],
    ["HD","GI"],["HB","GB"],["GI","GB"],
    ["GI","BT"],["BT","T1"],
    ["GB","BB"],["BB","T2"],
    ["BT","BB"],["T1","T2"],
    ["GB","BEL"],["BEL","BB"],
    ["T1","TCP"],["TCP","T2"],
    ["GI","DF"],["DF","BT"],
    ["GB","PF"],
    ["T1","TT"],["TT","TM"],["TM","TB"],["TB","T2"],
  ],
  allowedEdges: [
    ["MT","HD"],["MB","HB"],["MT","MB"],
    ["HD","GI"],["HB","GB"],["GI","GB"],
    ["GI","BT"],["BT","T1"],
    ["GB","BB"],["BB","T2"],
    ["BT","BB"],["T1","T2"],
    ["GB","BEL"],["BEL","BB"],
    ["T1","TCP"],["TCP","T2"],
    ["GI","DF"],["DF","BT"],
    ["GB","PF"],
    ["T1","TT"],["TT","TM"],["TM","TB"],["TB","T2"],
  ],
  zones: [
    { id: "head",   label: "Head/Collar", layer: "HEAD", anchors: ["MT","HD","HB","MB"],  colorToken: "HEAD_ZONE"     },
    { id: "collar", label: "Collar",      layer: "BODY", anchors: ["GI","BT","BB","GB"],  colorToken: "SHOULDER_ZONE" },
    { id: "loin",   label: "Loin",        layer: "BODY", anchors: ["BT","T1","T2","BB"],  colorToken: "LOIN_ZONE"     },
    { id: "belly",  label: "Belly",       layer: "BODY", anchors: ["GB","BB","BEL"],       colorToken: "BELLY_ZONE"    },
    { id: "tail",   label: "Tail",        layer: "BODY", anchors: ["T1","TCP","T2"],        colorToken: "LEG_ZONE"      },
  ],
};

// ── Boot — runs exactly once via ES module caching ─────────────────────────────

PrimalEngine.boot([ENGINE_COW, ENGINE_PIG, ENGINE_CHICKEN, ENGINE_LAMB, ENGINE_FISH]);
